USE test;

CREATE TABLE  student(NAME VARCHAR(10) PRIMARY KEY,
	PASSWORD VARCHAR(10) NOT NULL,
	id VARCHAR(10) NOT NULL);
	
INSERT INTO student(NAME,PASSWORD,id) VALUES("张三",123,1);
INSERT INTO student(NAME,PASSWORD,id) VALUES("李四",456,2);
INSERT INTO student(NAME,PASSWORD,id) VALUES("王五",789,3);
INSERT INTO student(NAME,PASSWORD,id) VALUES("赵六",1234,4);
INSERT INTO student(NAME,PASSWORD,id) VALUES("小明",4567,5);

ALTER TABLE student ORDER BY id DESC; 